version: '2.3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:16
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    container_name: app
    build:
      context: .
      args:
        POSTGRES_PORT: ${POSTGRES_PORT_DOCKER}
        DATABASE_URL: ${DATABASE_URL_DOCKER}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    depends_on:
      - postgres


#networks:
#  traefik-default:
#    external: true
